[ test ] Test CI

diff --git a/.github/workflows/ci-package.yml b/.github/workflows/ci-package.yml
--- a/.github/workflows/ci-package.yml
+++ b/.github/workflows/ci-package.yml
@@ -49,7 +49,7 @@ jobs:
           if [ "$CURR" == "$MAIN" ]; then
             echo 'upstream-matrix=["latest-pack-collection"]'
           else
-            echo 'upstream-matrix=["latest-pack-collection" ]' # "bleeding-edge-compiler"
+            echo 'upstream-matrix=["latest-pack-collection", "bleeding-edge-compiler"]'
           fi >> "$GITHUB_OUTPUT"
 
   build-and-test:
@@ -81,12 +81,10 @@ jobs:
                 <<< ${{ github.repository }})" >> "$GITHUB_ENV"
       - name: Build `${{ env.package_name }}`
         run: pack build ${{ env.package_name }}
-      # - name: Test `${{ env.package_name }}`
-      #   run: pack test ${{ env.package_name }}
+      - name: Test `${{ env.package_name }}`
+        run: pack test ${{ env.package_name }}
       - name: Gen SystemVerilog modules
-        run : pack run ${{ env.package_name }} --to "${{ env.GENERATION_DIR }}" -n 3    # Generate modules
-      # - name: Set up Node for actions
-      #   run: apt update && apt install -y nodejs
+        run : pack run ${{ env.package_name }} --to "${{ env.GENERATION_DIR }}" -n 42    # Generate modules
       - uses: actions/upload-artifact@v4
         id: generated-files-upload-step
         with:
@@ -110,14 +108,13 @@ jobs:
         run: sudo apt update && sudo apt install -y autoconf gperf make gcc g++ bison flex cmake python3
       - name: Set up iverilog
         run: |
-          rm -rf iverilog
           git clone https://github.com/steveicarus/iverilog.git
           cd iverilog
           sh autoconf.sh
           ./configure
           sudo make -j$(nproc)
           sudo make install
-      - name: Compile with Icarus Verilog
+      - name: Run Icarus Verilog
         run: |
           set +e
           for FILE in "${{ env.GENERATION_DIR }}"/*.sv; do
@@ -130,20 +127,14 @@ jobs:
             echo "$COMPILATION_OUTPUT"
 
             if [ $COMPILATION_EXIT_CODE -ne 0 ]; then
-              .github/workflows/filter_errors.sh "$COMPILATION_OUTPUT" ".github/workflows/iverilog-errors.txt"
+              .github/workflows/filter_errors.sh "$COMPILATION_OUTPUT" "(error|sorry): [\S ]+$" ".github/workflows/iverilog-errors.txt"
+              FILTER_ERRORS_EXIT_CODE=$?
+              if [ $FILTER_ERRORS_EXIT_CODE -ne 0 ]; then
+                echo "Exit."
+                exit 1
+              fi
             fi
 
-            echo "Simulating $FILE"
-
-            SIM_OUTPUT="$(vvp a.out 2>&1)"
-            SIM_EXIT_CODE=$?
-
-            echo "Exit code: $SIM_EXIT_CODE. Output:"
-            echo "$SIM_OUTPUT"
-
-            if [ $SIM_EXIT_CODE -ne 0 ]; then
-              .github/workflows/filter_errors.sh "$SIM_OUTPUT" ".github/workflows/iverilog-errors.txt"
-            fi
             echo "---------------------------------------------"
           done
 
@@ -165,10 +156,10 @@ jobs:
         run: |
           git clone https://github.com/MikePopoloski/slang.git
           cd slang
-          cmake -B build
-          cmake --build build -j$(nproc)
-          cmake --install build --strip
-      - name: Compile with Slang
+          sudo cmake -B build
+          sudo cmake --build build -j$(nproc)
+          sudo cmake --install build --strip
+      - name: Run Slang
         run: |
           set +e
           for FILE in "${{ env.GENERATION_DIR }}"/*.sv; do
@@ -181,25 +172,51 @@ jobs:
             echo "$COMPILATION_OUTPUT"
 
             if [ $COMPILATION_EXIT_CODE -ne 0 ]; then
-              .github/workflows/filter_errors.sh "$COMPILATION_OUTPUT" ".github/workflows/slang-errors.txt"
+              .github/workflows/filter_errors.sh "$COMPILATION_OUTPUT" "error: [\S ]+$" ".github/workflows/slang-errors.txt"
+              FILTER_ERRORS_EXIT_CODE=$?
+              if [ $FILTER_ERRORS_EXIT_CODE -ne 0 ]; then
+                echo "Exit."
+                exit 1
+              fi
             fi
+
             echo "---------------------------------------------"
           done
 
-  # test-with-verilator:
-  #   runs-on: ubuntu-latest
-  #   needs: build-and-test
-  #   steps:
-      # - name: Set up verilator
-      #   run: |
-      #     apt install -y perl help2man libfl2 libfl-dev zlib1g zlib1g-dev     # libgz zlibc
-      #     rm -rf verilator
-      #     git clone https://github.com/verilator/verilator   # Only first time
-      #     cd verilator
-      #     # git checkout master      # Use development branch (e.g. recent bug fixes)
-      #     git checkout stable      # Use most recent stable release
+  test-with-verilator:
+    runs-on: ubuntu-latest
+    needs: build-and-test
+    container:
+      image: verilator/verilator
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Download Generated Files
+        uses: actions/download-artifact@v4
+        with:
+          name: generated-modules
+          path: "${{ env.GENERATION_DIR }}"
+      - name: Run verilator
+        run: |
+          set +e
+          for FILE in "${{ env.GENERATION_DIR }}"/*.sv; do
+            echo "Processing $FILE"
 
-      #     autoconf
-      #     ./configure
-      #     make -j$(nproc)
-      #     make install
+            COMPILATION_OUTPUT="$(verilator --lint-only -Wno-fatal -Wno-lint -Wno-style +1800-2023ext+sv $FILE 2>&1)"
+            COMPILATION_EXIT_CODE=$?
+
+            echo "Exit code: $COMPILATION_EXIT_CODE. Output:"
+            echo "$COMPILATION_OUTPUT"
+
+            if [ $COMPILATION_EXIT_CODE -ne 0 ]; then
+              .github/workflows/filter_errors.sh "$COMPILATION_OUTPUT" "%Error(|\-[A-Z]+): [A-z0-9-_\/]+.sv:\d+:\d+:[\S ]*$" \
+                ".github/workflows/verilator-errors.txt"
+              FILTER_ERRORS_EXIT_CODE=$?
+              if [ $FILTER_ERRORS_EXIT_CODE -ne 0 ]; then
+                echo "Exit."
+                exit 1
+              fi
+            fi
+
+            echo "---------------------------------------------"
+          done
