[ test ] Test CI

diff --git a/.github/workflows/ci-package.yml b/.github/workflows/ci-package.yml
--- a/.github/workflows/ci-package.yml
+++ b/.github/workflows/ci-package.yml
@@ -155,86 +155,94 @@ jobs:
             echo "---------------------------------------------"
           done
 
-  # test-with-slang:
-  #   name: Test with Slang
-  #   needs: build-and-test
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Checkout
-  #       uses: actions/checkout@v4
-  #     - name: Download Generated Files
-  #       uses: actions/download-artifact@v4
-  #       with:
-  #         name: generated-modules
-  #         path: "${{ env.GENERATION_DIR }}"
-  #     - name: Install build tools
-  #       run: sudo apt update && sudo apt install -y autoconf gperf make gcc g++ bison flex cmake python3
-  #     - name: Set up slang
-  #       run: |
-  #         git clone https://github.com/MikePopoloski/slang.git
-  #         cd slang
-  #         sudo cmake -B build
-  #         sudo cmake --build build -j$(nproc)
-  #         sudo cmake --install build --strip
-  #     - name: Run Slang
-  #       run: |
-  #         set +e
-  #         for FILE in "${{ env.GENERATION_DIR }}"/*.sv; do
-  #           echo "Compiling $FILE"
+  test-with-slang:
+    name: Test with Slang
+    needs: build-and-test
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Download Generated Files
+        uses: actions/download-artifact@v4
+        with:
+          name: generated-modules
+          path: "${{ env.GENERATION_DIR }}"
+      - name: Install build tools
+        run: sudo apt update && sudo apt install -y autoconf gperf make gcc g++ bison flex cmake python3
+      - name: Set up slang
+        run: |
+          git clone https://github.com/MikePopoloski/slang.git
+          cd slang
+          sudo cmake -B build
+          sudo cmake --build build -j$(nproc)
+          sudo cmake --install build --strip
+      - name: Run Slang
+        run: |
+          set +e
+          for FILE in "${{ env.GENERATION_DIR }}"/*.sv; do
+            echo "Compiling $FILE"
 
-  #           COMPILATION_OUTPUT="$(slang -Weverything "$FILE" 2>&1)"
-  #           COMPILATION_EXIT_CODE=$?
+            COMPILATION_OUTPUT="$(slang -Weverything "$FILE" 2>&1)"
+            COMPILATION_EXIT_CODE=$?
 
-  #           echo "Exit code: $COMPILATION_EXIT_CODE. Output:"
-  #           echo "$COMPILATION_OUTPUT"
+            echo "Exit code: $COMPILATION_EXIT_CODE. Output:"
+            echo "$COMPILATION_OUTPUT"
 
-  #           if [ $COMPILATION_EXIT_CODE -ne 0 ]; then
-  #             .github/workflows/filter_errors.sh "$COMPILATION_OUTPUT" "error: [\S ]+$" ".github/workflows/slang-errors.txt"
-  #             FILTER_ERRORS_EXIT_CODE=$?
-  #             if [ $FILTER_ERRORS_EXIT_CODE -ne 0 ]; then
-  #               echo "Exit."
-  #               exit 1
-  #             fi
-  #           fi
+            if [ $COMPILATION_EXIT_CODE -ne 0 ]; then
+              .github/workflows/filter_errors.sh "$COMPILATION_OUTPUT" "error: [\S ]+$" ".github/workflows/slang-errors.txt"
+              FILTER_ERRORS_EXIT_CODE=$?
+              if [ $FILTER_ERRORS_EXIT_CODE -ne 0 ]; then
+                echo "Exit."
+                exit 1
+              fi
+            fi
 
-  #           echo "---------------------------------------------"
-  #         done
+            echo "---------------------------------------------"
+          done
 
-  # test-with-verilator:
-  #   name: Test with Verilator
-  #   runs-on: ubuntu-latest
-  #   needs: build-and-test
-  #   container:
-  #     image: verilator/verilator
-  #   steps:
-  #     - name: Checkout
-  #       uses: actions/checkout@v4
-  #     - name: Download Generated Files
-  #       uses: actions/download-artifact@v4
-  #       with:
-  #         name: generated-modules
-  #         path: "${{ env.GENERATION_DIR }}"
-  #     - name: Run verilator
-  #       run: |
-  #         set +e
-  #         for FILE in "${{ env.GENERATION_DIR }}"/*.sv; do
-  #           echo "Processing $FILE"
+  test-with-verilator:
+    name: Test with Verilator
+    runs-on: ubuntu-latest
+    needs: build-and-test
+    container:
+      image: verilator/verilator
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Download Generated Files
+        uses: actions/download-artifact@v4
+        with:
+          name: generated-modules
+          path: "${{ env.GENERATION_DIR }}"
+      - name: Run verilator
+        run: |
+          for FILE in "${{ env.GENERATION_DIR }}"/*.sv; do
+            set +e
+            echo "Compiling $FILE"
 
-  #           COMPILATION_OUTPUT="$(verilator --lint-only -Wno-fatal -Wno-lint -Wno-style +1800-2023ext+sv $FILE 2>&1)"
-  #           COMPILATION_EXIT_CODE=$?
+            rm -rf obj_dir
+            rm top.sv
+            cp $FILE top.sv
+            COMPILATION_OUTPUT="$(verilator --cc --exe .github/workflows/testbench.cpp --trace --timing -Wno-fatal -Wno-lint -Wno-style +1800-2023ext+sv top.sv 2>&1)"
+            COMPILATION_EXIT_CODE=$?
 
-  #           echo "Exit code: $COMPILATION_EXIT_CODE. Output:"
-  #           echo "$COMPILATION_OUTPUT"
+            echo "Exit code: $COMPILATION_EXIT_CODE. Output:"
+            echo "$COMPILATION_OUTPUT"
 
-  #           if [ $COMPILATION_EXIT_CODE -ne 0 ]; then
-  #             .github/workflows/filter_errors.sh "$COMPILATION_OUTPUT" "%Error(|\-[A-Z]+): [A-z0-9-_\/]+.sv:\d+:\d+:[\S ]*$" \
-  #               ".github/workflows/verilator-errors.txt"
-  #             FILTER_ERRORS_EXIT_CODE=$?
-  #             if [ $FILTER_ERRORS_EXIT_CODE -ne 0 ]; then
-  #               echo "Exit."
-  #               exit 1
-  #             fi
-  #           fi
+            if [ $COMPILATION_EXIT_CODE -ne 0 ]; then
+              .github/workflows/filter_errors.sh "$COMPILATION_OUTPUT" "%Error(|\-[A-Z]+): [A-z0-9-_\/]+.sv:\d+:\d+:[\S ]*$" \
+                ".github/workflows/verilator-errors.txt"
+              FILTER_ERRORS_EXIT_CODE=$?
+              if [ $FILTER_ERRORS_EXIT_CODE -ne 0 ]; then
+                echo "Exit."
+                exit 1
+              fi
+            else
+              echo "Simulating $FILE"
+              set -e
+              make -C obj_dir -f Vtop.mk Vtop
+              ./obj_dir/Vtop
+            fi
 
-  #           echo "---------------------------------------------"
-  #         done
+            echo "---------------------------------------------"
+          done
